//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementwareCommesse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBElementwareCommesseEntities : DbContext
    {
        public DBElementwareCommesseEntities()
            : base("name=DBElementwareCommesseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAB_COLONNE> TAB_COLONNE { get; set; }
        public virtual DbSet<TAB_CONFIGURAZIONE> TAB_CONFIGURAZIONE { get; set; }
        public virtual DbSet<TAB_CONFIGURAZIONE_SEZIONI> TAB_CONFIGURAZIONE_SEZIONI { get; set; }
        public virtual DbSet<TAB_ROW> TAB_ROW { get; set; }
        public virtual DbSet<TAB_SEZ> TAB_SEZ { get; set; }
    }
}
