//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementwareCommesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_CONFIGURAZIONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_CONFIGURAZIONE()
        {
            this.TAB_CONFIGURAZIONE_SEZIONI = new HashSet<TAB_CONFIGURAZIONE_SEZIONI>();
        }
    
        public int IDConfigurazione { get; set; }
        public string NomeConfigurazione { get; set; }
        public string DescrizioneCofigurazione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_CONFIGURAZIONE_SEZIONI> TAB_CONFIGURAZIONE_SEZIONI { get; set; }
    }
}
