//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElementwareCommesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_ROW
    {
        public int IDColonna { get; set; }
        public int IDRow { get; set; }
        public string Value { get; set; }
    }
}
